apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-backend-data
  namespace: todo-dev
  labels:
    app: todo-backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  # Minikube uses the "standard" StorageClass by default
  storageClassName: standard
